# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import prakticspeechApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_system', models.CharField(choices=[('1', 'speaker_recognition'), ('2', 'language_detection')], max_length=1)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('audioFile', models.FileField(upload_to=prakticspeechApp.models.get_upload_to)),
                ('hashData', models.CharField(max_length=255)),
                ('signalFFTData', models.CharField(max_length=255)),
                ('numberOfRows', models.IntegerField()),
                ('numberOfColumns', models.IntegerField()),
                ('signalFFTDataNPString', models.TextField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
