# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prakticspeechApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
