# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prakticspeechApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='numberOfColumns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='numberOfRows',
            field=models.IntegerField(default=0),
        ),
    ]
