# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prakticspeechApp', '0002_audiofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
