# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prakticspeechApp', '0002_auto_20170827_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='numpyDataType',
            field=models.CharField(default='float', max_length=255),
        ),
    ]
